---
title: "Dataset_2_Model"
author: "Malte Söhren"
date: "12/16/2020"
output: html_document
---

# Loading Packages 

```{r}
library(tidyverse)
library(DataExplorer)
library(caret)
library(caretEnsemble)
library(pROC)
library(gbm)
library(data.table)
library(superml)
```

```{r}
setwd("/Users/2egaa/Desktop/ng-BotClassifier/")
data_base <- read.csv("overview_labels.csv")
```

```{r}
data <- data_base %>%  select(c("bot", "freetext",  "ratioIneqUS",   "avgTime.min",    "outRatio",    "speeder", "time_1.1.1", "time_1.2.1", "time_2.1.1", "time_2.2.1", "time_2.3.1", "time_feedback", "time_feedback", "prol.prolific_score", "feedback"))
```

```{r}
data$bot[is.na(data$bot)] <- 0
data$bot[data$bot == 2] <- 1
data$bot[data$bot == 3] <- 1

data$bot <- as.factor(data$bot)

data$bot <- factor(data$bot, levels=c(0,1), labels=c("No", "Yes"))
data$speeder <- as.factor(data$speeder)
data$superspeeder <- as.factor(data$superspeeder)
data$retake <- as.factor(data$retake)
```

```{r}
data <- data %>% na.omit()
```

```{r}
data_glove_2 <- data %>% select(c(bot, feedback, quirk))
data_glove_2$feedback <- as.character(data_glove_2$feedback)
data_glove_2$text <- do.call(paste0, data_glove_2[2:3])
data_glove_2$bot <- as.integer(data_glove_2$bot)
```
